CH.SC.U4CSE24111-DARUNKUMAR J

Random Forest Exercise-1

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from google.colab import files

uploaded = files.upload()

# Read the dataset
data = pd.read_csv("random_forest_fruit_dataset.csv")

print("Dataset:")
print(data)

# Separate features and target
X = data[["Weight", "Sweetness"]]
y = data["Fruit"]

# Convert fruit names to numerical labels
fruit_names = ["Apple", "Banana", "Orange", "Mango"]

y = y.map({
    "Apple": 0,
    "Banana": 1,
    "Orange": 2,
    "Mango": 3
})

# Split dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=5,
    stratify=y
)

# Create Random Forest Classifier
model = RandomForestClassifier(
    n_estimators=10,
    criterion="entropy",
    random_state=0
)

# Train the model
model.fit(X_train, y_train)

# Predict test data
y_pred = model.predict(X_test)

# Evaluation
print("\nRandom Forest Classifier")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy Score:", accuracy)
print("Accuracy in Percentage:", accuracy * 100, "%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=fruit_names,
        zero_division=0
    )
)

# Predict a new fruit
new_fruit = np.array([[150, 7]])

prediction = model.predict(new_fruit)

print("\nNew Fruit:")
print("Weight:", new_fruit[0][0])
print("Sweetness:", new_fruit[0][1])
print("Predicted Fruit:", fruit_names[int(prediction[0])])

# Show prediction from every individual tree
print("\nPredictions from Individual Trees:")

tree_predictions = []

for i, tree in enumerate(model.estimators_):
    tree_prediction = tree.predict(new_fruit)[0]
    tree_predictions.append(int(tree_prediction))

    print(
        "Tree", i + 1,
        "->",
        fruit_names[int(tree_prediction)]
    )

# Majority voting
votes = np.bincount(tree_predictions, minlength=4)

print("\nMajority Voting:")
print("Apple votes :", votes[0])
print("Banana votes:", votes[1])
print("Orange votes:", votes[2])
print("Mango votes :", votes[3])

majority_class = np.argmax(votes)

print("\nFinal Prediction:", fruit_names[majority_class])

Saving random_forest_fruit_dataset.csv to random_forest_fruit_dataset.csv
Dataset:
    Weight  Sweetness   Fruit
0      150          7   Apple
1      160          8   Apple
2      145          6   Apple
3      155          7   Apple
4      120          9  Banana
5      110          8  Banana
6      115          9  Banana
7      125          8  Banana
8      180          6  Orange
9      190          5  Orange
10     175          6  Orange
11     185          5  Orange
12     200          8   Mango
13     210          9   Mango
14     195          8   Mango
15     205          9   Mango

Random Forest Classifier

Confusion Matrix:
[[0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 2]]

Accuracy Score: 0.6
Accuracy in Percentage: 60.0 %

Classification Report:
              precision    recall  f1-score   support

       Apple       0.00      0.00      0.00         1
      Banana       0.50      1.00      0.67         1
      Orange       0.00      0.00      0.00         1
       Mango       1.00 

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
